# Generated by Django 5.2.1 on 2026-06-18 19:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً خانه، محل کار', max_length=60, verbose_name='عنوان آدرس')),
                ('receiver', models.CharField(max_length=150, verbose_name='نام گیرنده')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با ۰۹ شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=60, verbose_name='استان')),
                ('city', models.CharField(max_length=60, verbose_name='شهر')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='نشانی کامل')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
