# Generated by Django 5.2.1 on 2026-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'عادی'), ('colleague', 'همکار')], default='normal', help_text='کاربران همکار قیمت ویژهٔ همکاری را می\u200cبینند', max_length=10, verbose_name='نوع کاربر'),
        ),
    ]
