# Generated by Django 5.2.1 on 2026-06-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='عنوان')),
                ('position', models.CharField(choices=[('hero', 'اسلایدر بزرگ (بالای صفحه)'), ('promo', 'بنر کوچک (تبلیغاتی)')], default='hero', max_length=10, verbose_name='جایگاه')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('link', models.CharField(blank=True, help_text='اختیاری؛ مثلاً /products/ یا آدرس کامل', max_length=300, verbose_name='لینک مقصد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['position', 'order', '-id'],
            },
        ),
    ]
