# Generated by Django 5.2.1 on 2026-07-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ویژگی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('unit', models.CharField(blank=True, help_text='اختیاری؛ مثلاً مگاپیکسل یا متر', max_length=30, verbose_name='واحد')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='نمایش در فیلترها')),
                ('show_in_specs', models.BooleanField(default=True, verbose_name='نمایش در مشخصات فنی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('categories', models.ManyToManyField(blank=True, help_text='خالی بگذارید تا برای همهٔ دسته\u200cها نمایش داده شود', related_name='attributes', to='shop.category', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shop.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی',
                'ordering': ['attribute', 'order', 'value'],
                'unique_together': {('attribute', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.attributevalue', verbose_name='ویژگی\u200cها'),
        ),
    ]
