# Generated by Django 5.2.1 on 2026-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_attribute_attributevalue_product_attribute_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='call_for_price',
            field=models.BooleanField(default=False, help_text='برای محصولات با قیمت دلاری/متغیر؛ به\u200cجای قیمت، پیام «تماس بگیرید» نمایش داده می\u200cشود', verbose_name='استعلام قیمت (تماس بگیرید)'),
        ),
        migrations.AddField(
            model_name='product',
            name='colleague_price',
            field=models.BigIntegerField(blank=True, help_text='قیمت ویژهٔ کاربران همکار؛ خالی بگذارید تا همان قیمت عادی اعمال شود', null=True, verbose_name='قیمت همکار (ریال)'),
        ),
    ]
