# Generated by Django 5.2.1 on 2026-06-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت (ریال)')], default='percent', max_length=10, verbose_name='نوع تخفیف')),
                ('value', models.BigIntegerField(help_text='درصد (۰ تا ۱۰۰) یا مبلغ ریالی', verbose_name='مقدار')),
                ('min_amount', models.BigIntegerField(default=0, verbose_name='حداقل مبلغ سبد (ریال)')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='معتبر از')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='معتبر تا')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='خالی = نامحدود', null=True, verbose_name='حداکثر دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده\u200cشده')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ تخفیف (ریال)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ قابل پرداخت (ریال)'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='کد تخفیف'),
        ),
    ]
