# Generated by Django 5.2.1 on 2026-06-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon_order_discount_alter_order_total_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت واحد (ریال)'),
        ),
    ]
