# Generated by Django 5.2.1 on 2026-06-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authority',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد authority زرین\u200cپال'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شماره پیگیری'),
        ),
    ]
