# Generated by Django 5.2.1 on 2026-07-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_authority_order_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='کد رهگیری پست یا تیپاکس؛ پس از ارسال سفارش وارد کنید', max_length=50, verbose_name='کد رهگیری پستی'),
        ),
    ]
